@startuml
object 租户
object 组织
object 组织类别
object 员工
object 岗位

组织 "0..*" -- "1..1" 组织类别
员工 "0..*" -- "1..1" 组织
组织类别 "0..1 上级" -- "0..* 下级" 组织类别
员工 "0..*" -- "0..*" 岗位

note "-企业\n-开发中心\n-开发组\n-直属部门\n-..." as n1
n1 .. 组织类别
note "{\n- 开发组的上级只能是开发中心\n- 开发中心和直属部门的上级只能是企业\n- 企业没有上级\n- 开发组和直属部门没有下级\n}" as n2
n2 .. 组织
note "{只有企业才能作为租户}" as n3
n3 .. 租户
note "系统中所有实体都\n是属于某个租户，\n以便隔离不同租户数据\n为了简洁，不一一画出" as n4
n4 .. 租户
note "-管理员\n-人事人员\n-..." as n5
n5 .. 岗位


@enduml
